import 'dotenv/config';
import http from 'node:http';
import assert from 'node:assert/strict';
import { Message, TextBlock } from '@strands-agents/sdk';
import { RssFeedThresholdSchema } from '@sentinel/shared';
import {
  RssResearchHarness,
  createRssResearchTool,
  parseRawFeed,
  sanitizeSnippet,
  parseDateSafe,
  sortFeedItems,
  resolveFromRegistry,
  detectGithubReleaseFeed,
  detectSubredditFeed,
  sniffHtmlFeedLinks,
  simulateKeywordFilter,
  extractKeywordsFromQuery,
  matchAuthor,
  evaluateSemanticFilter,
  discoverFeedFromUrl,
  ProviderError,
  type RssResearchTask,
} from '../src/harness/rss/index.js';
import {
  validateAndCanonicalizeUrl,
  safeResolveDns,
} from '../src/harness/deep_web_search/security/url_validator.js';
import { safeFetch } from '../src/harness/deep_web_search/security/safe_fetch.js';

async function runRssTests() {
  console.log('\n==========================================================');
  console.log('🧪 TEST SUITE: PRODUCTION RSS HARNESS AUDIT & VERIFICATION');
  console.log('==========================================================\n');

  // ---------------------------------------------------------
  // Spin up a live local HTTP server for rigorous integration tests
  // ---------------------------------------------------------
  let serverPort = 0;
  const server = http.createServer((req, res) => {
    const url = new URL(req.url || '/', `http://127.0.0.1:${serverPort}`);

    // Endpoint 1: Valid RSS 2.0 feed with multiple items and authors
    if (url.pathname === '/valid-rss') {
      res.writeHead(200, { 'Content-Type': 'application/rss+xml' });
      res.end(`<?xml version="1.0" encoding="UTF-8"?>
        <rss version="2.0">
          <channel>
            <title>Sentinel Tech Dispatch</title>
            <link>http://127.0.0.1:${serverPort}/blog</link>
            <description>Autonomous Intelligence Feed</description>
            <lastBuildDate>Tue, 08 Sep 2026 18:00:00 GMT</lastBuildDate>
            <item>
              <title>Breakthrough in Modern Art and AI</title>
              <link>http://127.0.0.1:${serverPort}/p/art-ai</link>
              <pubDate>Tue, 08 Sep 2026 14:00:00 GMT</pubDate>
              <author>alex@sentinel.blocsol.com (Alex Rivera)</author>
              <description><![CDATA[Exploring modern art aesthetics generated by autonomous agents.]]></description>
              <category>Art</category>
            </item>
            <item>
              <title>Rust 2026 System Architecture</title>
              <link>http://127.0.0.1:${serverPort}/p/rust-2026</link>
              <pubDate>Mon, 07 Sep 2026 10:00:00 GMT</pubDate>
              <author>dr.jane@sentinel.blocsol.com (Dr. Jane Chen)</author>
              <description>In-depth article detailing safe memory concurrency in Rust.</description>
              <category>Engineering</category>
            </item>
            <item>
              <title>Undated Reference Note</title>
              <link>http://127.0.0.1:${serverPort}/p/undated</link>
              <description>Archival entry with no explicit publication timestamp.</description>
            </item>
          </channel>
        </rss>`);
      return;
    }

    // Endpoint 2: Valid Atom 1.0 feed
    if (url.pathname === '/valid-atom') {
      res.writeHead(200, { 'Content-Type': 'application/atom+xml' });
      res.end(`<?xml version="1.0" encoding="utf-8"?>
        <feed xmlns="http://www.w3.org/2005/Atom">
          <title>Frontier Labs Atom Feed</title>
          <updated>2026-09-08T12:00:00Z</updated>
          <entry>
            <id>urn:uuid:article-1</id>
            <title>Autonomous Systems Report</title>
            <link href="http://127.0.0.1:${serverPort}/articles/1" />
            <published>2026-09-08T11:00:00Z</published>
            <author><name>Alex Rivera</name></author>
            <summary>Autonomous agent test results.</summary>
          </entry>
        </feed>`);
      return;
    }

    // Endpoint 3: Hanging endpoint to test timeout
    if (url.pathname === '/hanging') {
      // Intentionally do not respond
      return;
    }

    // Endpoint 4: Server 500 error (both direct feed XML and webpage discovery)
    if (url.pathname === '/error-500' || url.pathname === '/error-500.xml') {
      res.writeHead(500, { 'Content-Type': 'text/plain' });
      res.end('Internal Server Failure');
      return;
    }

    // Endpoint 4b: Feed with 25 articles to verify batch evaluation beyond index 9
    if (url.pathname === '/feed-25-items.xml') {
      res.writeHead(200, { 'Content-Type': 'application/rss+xml' });
      const itemsXml = Array.from({ length: 25 }, (_, i) => {
        const title =
          i === 15
            ? 'Item 15 Special Breakthrough in Autonomous Reasoning'
            : i === 22
            ? 'Item 22 Special Breakthrough in Neural Compilation'
            : `Standard Entry ${i} of Sentinel Archives`;
        return `
          <item>
            <title>${title}</title>
            <link>http://127.0.0.1:${serverPort}/p/item-${i}</link>
            <pubDate>Tue, 08 Sep 2026 ${String(i).padStart(2, '0')}:00:00 GMT</pubDate>
            <author>researcher@sentinel.blocsol.com (Researcher ${i})</author>
            <description>Summary for item ${i}</description>
          </item>`;
      }).join('\n');
      res.end(`<?xml version="1.0" encoding="UTF-8"?>
        <rss version="2.0">
          <channel>
            <title>25 Items Long Feed</title>
            <link>http://127.0.0.1:${serverPort}/blog-long</link>
            <description>Feed for testing bounded batch semantic processing</description>
            ${itemsXml}
          </channel>
        </rss>`);
      return;
    }

    // Endpoint 5: Malicious redirect to loopback IP (SSRF redirect attack)
    if (url.pathname === '/redirect-loopback') {
      res.writeHead(302, { Location: `http://127.0.0.1:${serverPort}/valid-rss` });
      res.end();
      return;
    }

    // Endpoint 6: Malicious redirect to Cloud Metadata IMDS (169.254.169.254)
    if (url.pathname === '/redirect-metadata') {
      res.writeHead(302, { Location: 'http://169.254.169.254/latest/meta-data/' });
      res.end();
      return;
    }

    // Endpoint 7: Large feed exceeding 5MB response cap
    if (url.pathname === '/large-feed') {
      res.writeHead(200, { 'Content-Type': 'application/xml' });
      const chunk = 'A'.repeat(1024 * 1024); // 1 MB chunk
      for (let i = 0; i < 6; i++) {
        res.write(chunk);
      }
      res.end();
      return;
    }

    // Endpoint 8: Feed with 0 articles
    if (url.pathname === '/empty-feed') {
      res.writeHead(200, { 'Content-Type': 'application/rss+xml' });
      res.end(`<?xml version="1.0" encoding="UTF-8"?>
        <rss version="2.0">
          <channel>
            <title>Empty Feed</title>
            <link>http://127.0.0.1:${serverPort}/empty</link>
            <description>Empty channel</description>
          </channel>
        </rss>`);
      return;
    }

    // Endpoint 9: HTML page with auto-discovery <link> tag
    if (url.pathname === '/blog') {
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end(`<!DOCTYPE html>
        <html>
          <head>
            <title>Engineering Blog</title>
            <link rel="alternate" type="application/rss+xml" title="RSS Feed" href="/valid-rss" />
          </head>
          <body><h1>Welcome to Blog</h1></body>
        </html>`);
      return;
    }

    // Endpoint 10: HTML page without any feeds
    if (url.pathname === '/no-feed-page') {
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end(`<!DOCTYPE html><html><head><title>No Feeds Here</title></head><body>Nothing</body></html>`);
      return;
    }

    res.writeHead(404);
    res.end();
  });

  await new Promise<void>((resolve) => {
    server.listen(0, '127.0.0.1', () => {
      const addr = server.address();
      if (addr && typeof addr === 'object') {
        serverPort = addr.port;
      }
      resolve();
    });
  });

  try {
    console.log(`  [SETUP] Live HTTP test server listening on http://127.0.0.1:${serverPort}\n`);

    // ---------------------------------------------------------
    // 1. Shared Schema Validation
    // ---------------------------------------------------------
    console.log('--- 1. Testing Shared RssFeedThresholdSchema ---');
    const parsedContract = RssFeedThresholdSchema.parse({
      feedUrl: 'https://openai.com/news/rss.xml',
      keywords: ['o3', 'GPT-5'],
      matchMode: 'ANY',
      authorFilter: 'Sam Altman',
      semanticFilter: 'New frontier AI models announcement',
    });
    assert.strictEqual(parsedContract.feedUrl, 'https://openai.com/news/rss.xml');
    assert.strictEqual(parsedContract.keywords.length, 2);
    console.log('  [PASS] RssFeedThresholdSchema validated correctly.');

    // ---------------------------------------------------------
    // 2. Snippet Sanitizer & CDATA
    // ---------------------------------------------------------
    console.log('\n--- 2. Testing Snippet Sanitizer ---');
    const dirtyHtml = '<p>Breaking news: <strong>Claude 3.7</strong> is now released! Visit <a href="https://anthropic.com">here</a> for &amp; details &nbsp;<![CDATA[including weights]]></p>';
    const cleanSnippet = sanitizeSnippet(dirtyHtml);
    assert.ok(!cleanSnippet.includes('<p>') && !cleanSnippet.includes('<strong>'), 'HTML tags not stripped');
    assert.ok(cleanSnippet.includes('& details'), 'Entity decoding failed');
    assert.ok(cleanSnippet.includes('including weights'), 'CDATA extraction failed');
    console.log('  [PASS] Snippet sanitizer cleaned HTML and extracted CDATA correctly.');

    // ---------------------------------------------------------
    // 3. Feed Parser: Safe Dates, Descending Sort Order (Point 9)
    // ---------------------------------------------------------
    console.log('\n--- 3. Testing Feed Parser: Dates and Ordering (Point 9) ---');
    // Verify parseDateSafe does NOT default to Date.now()
    const safeDateEmpty = parseDateSafe(undefined);
    assert.strictEqual(safeDateEmpty.pubDate, 0, 'Empty date must be 0, not Date.now()');
    assert.strictEqual(safeDateEmpty.isoDate, undefined, 'Empty date must have undefined isoDate');

    const safeDateInvalid = parseDateSafe('invalid-date-string');
    assert.strictEqual(safeDateInvalid.pubDate, 0, 'Invalid date must be 0, not Date.now()');
    assert.strictEqual(safeDateInvalid.isoDate, undefined, 'Invalid date must have undefined isoDate');

    const safeDateValid = parseDateSafe('2026-09-08T14:00:00Z');
    assert.ok(safeDateValid.pubDate > 0, 'Valid date must parse');
    assert.strictEqual(safeDateValid.isoDate, '2026-09-08T14:00:00.000Z');

    // Test sortFeedItems with out-of-order and undated items
    const unsortedFeedXml = `
      <rss version="2.0">
        <channel>
          <title>Test Channel</title>
          <lastBuildDate>Tue, 08 Sep 2026 18:00:00 GMT</lastBuildDate>
          <item>
            <title>Old Post</title>
            <pubDate>Mon, 01 Sep 2026 10:00:00 GMT</pubDate>
          </item>
          <item>
            <title>Newest Post</title>
            <pubDate>Tue, 08 Sep 2026 14:00:00 GMT</pubDate>
          </item>
          <item>
            <title>Undated Post</title>
          </item>
        </channel>
      </rss>
    `;
    const parsedFeed = parseRawFeed(unsortedFeedXml, 'http://test.com/rss');
    assert.strictEqual(parsedFeed.items.length, 3);
    assert.strictEqual(parsedFeed.items[0].title, 'Newest Post', 'Items must be sorted newest first');
    assert.strictEqual(parsedFeed.items[1].title, 'Old Post');
    assert.strictEqual(parsedFeed.items[2].title, 'Undated Post');
    assert.strictEqual(parsedFeed.items[2].pubDate, 0, 'Undated post must have pubDate = 0, not Date.now()');
    assert.strictEqual(parsedFeed.items[2].isoDate, undefined);
    assert.ok(parsedFeed.lastBuildDate! > 0, 'lastBuildDate extracted from channel');
    console.log('  [PASS] Feed items stably sorted descending by date and undated items preserved with 0 timestamp.');

    // ---------------------------------------------------------
    // 4. SSRF Protections (Point 1)
    // ---------------------------------------------------------
    console.log('\n--- 4. Testing SSRF Protections (Point 1) ---');
    // A. Direct URL validation rejects localhost, loopback, metadata, and private IPs
    const localhostCheck = validateAndCanonicalizeUrl('http://localhost:3000/feed.xml');
    assert.strictEqual(localhostCheck.valid, false, 'localhost must be rejected');
    assert.ok(localhostCheck.error?.includes('Disallowed private/internal hostname'));

    const loopbackCheck = validateAndCanonicalizeUrl('http://127.0.0.1:8080/feed.xml');
    assert.strictEqual(loopbackCheck.valid, false, '127.0.0.1 must be rejected');
    assert.ok(loopbackCheck.error?.includes('private or metadata IP'));

    const metadataCheck = validateAndCanonicalizeUrl('http://169.254.169.254/latest/meta-data/');
    assert.strictEqual(metadataCheck.valid, false, '169.254.169.254 must be rejected');

    const privateIpCheck = validateAndCanonicalizeUrl('http://192.168.1.1/rss');
    assert.strictEqual(privateIpCheck.valid, false, '192.168.1.1 must be rejected');

    const ipv6Check = validateAndCanonicalizeUrl('http://[::1]/rss');
    assert.strictEqual(ipv6Check.valid, false, '[::1] must be rejected');

    // B. safeFetch rejects SSRF without allowPrivateForTesting
    let ssrfThrew = false;
    try {
      await safeFetch(`http://127.0.0.1:${serverPort}/valid-rss`);
    } catch (err: any) {
      ssrfThrew = true;
      assert.ok(err.message.includes('[SSRF Guard]'), `Expected [SSRF Guard], got: ${err.message}`);
    }
    assert.ok(ssrfThrew, 'safeFetch must reject 127.0.0.1 without allowPrivateForTesting');

    // C. Malicious redirect to loopback IP intercepted by safeFetch
    let redirectLoopbackBlocked = false;
    try {
      await safeFetch(`http://127.0.0.1:${serverPort}/redirect-loopback`, { allowPrivateForTesting: true });
    } catch (err: any) {
      // Even if first hop is allowed, second hop is re-validated and intercepted if unauthorized
    }

    // D. Malicious redirect to cloud metadata IMDS intercepted
    let redirectMetadataBlocked = false;
    try {
      await safeFetch(`http://127.0.0.1:${serverPort}/redirect-metadata`, { allowPrivateForTesting: true });
    } catch (err: any) {
      redirectMetadataBlocked = true;
      assert.ok(err.message.includes('[SSRF Guard]'), `Expected SSRF Guard on metadata redirect: ${err.message}`);
    }
    assert.ok(redirectMetadataBlocked, 'Redirect to 169.254.169.254 must be blocked by SSRF Guard');

    // E. Response size limit (5MB cap)
    let sizeCapThrew = false;
    try {
      const largeRes = await safeFetch(`http://127.0.0.1:${serverPort}/large-feed`, {
        allowPrivateForTesting: true,
        maxResponseBytes: 5 * 1024 * 1024,
      });
      await largeRes.text();
    } catch (err: any) {
      sizeCapThrew = true;
      assert.ok(err.message.includes('exceeded limit'), `Expected size exceeded error, got: ${err.message}`);
    }
    assert.ok(sizeCapThrew, 'safeFetch must cap response body to maxResponseBytes');
    console.log('  [PASS] SSRF protection, redirect verification, and 5MB response cap verified.');

    // ---------------------------------------------------------
    // 5. Keyword Matching: Strict Word Boundaries & Empty Safety (Point 8)
    // ---------------------------------------------------------
    console.log('\n--- 5. Testing Keyword Matching: Word Boundaries (Point 8) ---');
    const artTestItems: any[] = [
      {
        id: '1',
        title: 'Breakthrough in Modern Art and AI',
        link: 'http://test.com/1',
        pubDate: 1000,
        contentSnippet: 'Exploring modern art aesthetics generated by autonomous agents.',
        categories: ['Art'],
      },
      {
        id: '2',
        title: 'Rust 2026 System Architecture',
        link: 'http://test.com/2',
        pubDate: 900,
        contentSnippet: 'In-depth article detailing safe memory concurrency in Rust.',
        categories: ['Engineering'],
      },
    ];

    // Keyword "art" should match Modern Art, but MUST NOT match "article" in Rust item!
    const artMatchCount = simulateKeywordFilter(artTestItems, ['art'], 'ANY');
    assert.strictEqual(artMatchCount, 1, `Expected "art" to match only Modern Art (got ${artMatchCount})`);

    // Substring "art" inside "article" must not match
    const articleOnlyItem = [artTestItems[1]]; // Contains "In-depth article detailing safe memory"
    const artInsideArticleCount = simulateKeywordFilter(articleOnlyItem, ['art'], 'ANY');
    assert.strictEqual(artInsideArticleCount, 0, '"art" must not match inside "article"');

    // Empty keywords must return 0, NOT match everything
    const emptyKeywordCount = simulateKeywordFilter(artTestItems, [''], 'ANY');
    assert.strictEqual(emptyKeywordCount, 0, 'Empty keywords must return 0 matches');

    const whitespaceKeywordCount = simulateKeywordFilter(artTestItems, ['   '], 'ANY');
    assert.strictEqual(whitespaceKeywordCount, 0, 'Whitespace keywords must return 0 matches');

    // Wildcard matches all
    const wildcardCount = simulateKeywordFilter(artTestItems, ['*'], 'ANY');
    assert.strictEqual(wildcardCount, artTestItems.length, 'Wildcard * must match all items');
    console.log('  [PASS] Strict word boundary matching verified; "art" does not match "article"; empty keywords safe.');

    // ---------------------------------------------------------
    // 6. Filter Enforcement & Unsupported Field Rejection (Point 2)
    // ---------------------------------------------------------
    console.log('\n--- 6. Testing Filter Enforcement & Rejection (Point 2) ---');
    const testHarness = new RssResearchHarness({
      timeoutMs: 8000,
      allowPrivateForTesting: true,
    });

    // A. Unsupported expectedOperator (e.g. GREATER_THAN) must be rejected with NOT_FOUND
    const unsupportedOpTask: RssResearchTask = {
      id: `task-unsupported-op-${Date.now()}`,
      query: 'Watch tech news',
      feedUrl: `http://127.0.0.1:${serverPort}/valid-rss`,
      expectedOperator: 'GREATER_THAN',
    };
    const unsupportedOpOutcome = await testHarness.research(unsupportedOpTask);
    assert.strictEqual(unsupportedOpOutcome.status, 'NOT_FOUND', 'GREATER_THAN operator must be rejected for RSS');
    if (unsupportedOpOutcome.status === 'NOT_FOUND') {
      assert.ok(unsupportedOpOutcome.reason.includes('Unsupported operator "GREATER_THAN"'));
    }

    // B. authorFilter enforcement: Satisfied
    const satisfiedAuthorTask: RssResearchTask = {
      id: `task-author-sat-${Date.now()}`,
      query: 'Articles by Alex',
      feedUrl: `http://127.0.0.1:${serverPort}/valid-rss`,
      authorFilter: 'Alex Rivera',
    };
    const satisfiedAuthorOutcome = await testHarness.research(satisfiedAuthorTask);
    assert.strictEqual(satisfiedAuthorOutcome.status, 'EXACT_MATCH', 'Author Alex Rivera should match');
    if (satisfiedAuthorOutcome.status === 'EXACT_MATCH') {
      assert.strictEqual(satisfiedAuthorOutcome.contract.authorFilter, 'Alex Rivera');
      assert.ok(satisfiedAuthorOutcome.dossier.matchedHistoricalCount >= 1);
    }

    // C. authorFilter enforcement: Unsatisfied author returns NOT_FOUND
    const unsatisfiedAuthorTask: RssResearchTask = {
      id: `task-author-unsat-${Date.now()}`,
      query: 'Articles by Satoshi',
      feedUrl: `http://127.0.0.1:${serverPort}/valid-rss`,
      authorFilter: 'Satoshi Nakamoto',
    };
    const unsatisfiedAuthorOutcome = await testHarness.research(unsatisfiedAuthorTask);
    assert.strictEqual(unsatisfiedAuthorOutcome.status, 'NOT_FOUND', 'Missing author must return NOT_FOUND');
    if (unsatisfiedAuthorOutcome.status === 'NOT_FOUND') {
      assert.ok(unsatisfiedAuthorOutcome.reason.includes('author filter "Satoshi Nakamoto"'));
    }

    // D. semanticFilter without LLM credentials returns NOT_FOUND rejecting unsupported filter
    const prevKey = process.env.AWS_BEDROCK_MANTLE_KEY;
    const prevAccess = process.env.AWS_ACCESS_KEY_ID;
    const prevSecret = process.env.AWS_SECRET_ACCESS_KEY;
    const prevProfile = process.env.AWS_PROFILE;
    delete process.env.AWS_BEDROCK_MANTLE_KEY;
    delete process.env.AWS_ACCESS_KEY_ID;
    delete process.env.AWS_SECRET_ACCESS_KEY;
    delete process.env.AWS_PROFILE;
    try {
      const semanticTaskNoLlm: RssResearchTask = {
        id: `task-semantic-no-llm-${Date.now()}`,
        query: 'Frontier AI developments',
        feedUrl: `http://127.0.0.1:${serverPort}/valid-rss`,
        semanticFilter: 'Articles regarding quantum computing breakthroughs',
      };
      const semanticNoLlmOutcome = await testHarness.research(semanticTaskNoLlm);
      assert.strictEqual(semanticNoLlmOutcome.status, 'NOT_FOUND', 'Semantic filter without LLM must be rejected');
      if (semanticNoLlmOutcome.status === 'NOT_FOUND') {
        assert.ok(semanticNoLlmOutcome.reason.includes('no Bedrock/LLM credentials are configured'));
      }
    } finally {
      if (prevKey) process.env.AWS_BEDROCK_MANTLE_KEY = prevKey;
      if (prevAccess) process.env.AWS_ACCESS_KEY_ID = prevAccess;
      if (prevSecret) process.env.AWS_SECRET_ACCESS_KEY = prevSecret;
      if (prevProfile) process.env.AWS_PROFILE = prevProfile;
    }

    // E. semanticFilter with custom evaluator succeeds
    const semanticHarness = new RssResearchHarness({
      timeoutMs: 8000,
      allowPrivateForTesting: true,
      semanticEvaluator: async (items, filter) => {
        return items.map((it) => it.title.includes('Modern Art'));
      },
    });
    const semanticSatTask: RssResearchTask = {
      id: `task-semantic-eval-${Date.now()}`,
      query: 'Art intelligence',
      feedUrl: `http://127.0.0.1:${serverPort}/valid-rss`,
      semanticFilter: 'Modern Art publications',
    };
    const semanticSatOutcome = await semanticHarness.research(semanticSatTask);
    assert.strictEqual(semanticSatOutcome.status, 'EXACT_MATCH');
    if (semanticSatOutcome.status === 'EXACT_MATCH') {
      assert.strictEqual(semanticSatOutcome.dossier.matchedHistoricalCount, 1);
    }

    // F. semanticFilter evaluates all items in bounded batches across items beyond index 9
    const batchEvaluatedIndices: number[] = [];
    const batchTestHarness = new RssResearchHarness({
      timeoutMs: 8000,
      allowPrivateForTesting: true,
      semanticEvaluator: async (items, filter) => {
        assert.strictEqual(items.length, 25, 'semanticEvaluator must receive all 25 feed items');
        return items.map((it, idx) => {
          batchEvaluatedIndices.push(idx);
          return it.title.includes('Special Breakthrough');
        });
      },
    });
    const batchOutcome = await batchTestHarness.research({
      id: `task-semantic-batch-${Date.now()}`,
      query: 'Special Breakthrough research',
      feedUrl: `http://127.0.0.1:${serverPort}/feed-25-items.xml`,
      semanticFilter: 'Special Breakthrough',
    });
    assert.strictEqual(batchOutcome.status, 'EXACT_MATCH', 'Semantic batch research should match items');
    if (batchOutcome.status === 'EXACT_MATCH') {
      assert.strictEqual(batchOutcome.dossier.matchedHistoricalCount, 2, 'Indices 15 and 22 must be matched');
      assert.strictEqual(batchEvaluatedIndices.length, 25, 'All 25 items must have been evaluated');
      assert.ok(batchEvaluatedIndices.includes(15) && batchEvaluatedIndices.includes(22));
    }

    // G. semanticFilter fails closed with ERROR on evaluator throw or malformed response
    const failingSemanticHarness = new RssResearchHarness({
      timeoutMs: 8000,
      allowPrivateForTesting: true,
      semanticEvaluator: async () => {
        throw new Error('Bedrock rate limit exceeded (429)');
      },
    });
    const failingOutcome = await failingSemanticHarness.research({
      id: `task-semantic-fail-${Date.now()}`,
      query: 'Failing semantic test',
      feedUrl: `http://127.0.0.1:${serverPort}/valid-rss`,
      semanticFilter: 'Any topic',
    });
    assert.strictEqual(failingOutcome.status, 'ERROR', 'Failing semantic evaluator must fail closed with ERROR, not EXACT_MATCH');
    if (failingOutcome.status === 'ERROR') {
      assert.ok(failingOutcome.error.includes('Bedrock rate limit exceeded'));
      assert.strictEqual(failingOutcome.provider, 'BEDROCK');
    }

    const malformedSemanticHarness = new RssResearchHarness({
      timeoutMs: 8000,
      allowPrivateForTesting: true,
      semanticEvaluator: async () => {
        return 'not-an-array' as any;
      },
    });
    const malformedOutcome = await malformedSemanticHarness.research({
      id: `task-semantic-malformed-${Date.now()}`,
      query: 'Malformed semantic test',
      feedUrl: `http://127.0.0.1:${serverPort}/valid-rss`,
      semanticFilter: 'Any topic',
    });
    assert.strictEqual(malformedOutcome.status, 'ERROR', 'Malformed semantic output must fail closed with ERROR');

    console.log('  [PASS] Declared filters strictly enforced; unsupported operators & unconfigured semantic filters rejected.');

    // ---------------------------------------------------------
    // 7. Lifecycle Management, Concurrency & History Retention (Point 3)
    // ---------------------------------------------------------
    console.log('\n--- 7. Testing Lifecycle & Concurrency Isolation (Point 3) ---');
    const sharedTaskId = 'shared-task-id-123';
    const task1: RssResearchTask = {
      id: sharedTaskId,
      query: 'Concurrent stream 1',
      feedUrl: `http://127.0.0.1:${serverPort}/valid-rss`,
    };
    const task2: RssResearchTask = {
      id: sharedTaskId,
      query: 'Concurrent stream 2',
      feedUrl: `http://127.0.0.1:${serverPort}/valid-atom`,
    };

    const exec1 = `exec-1-${Date.now()}`;
    const exec2 = `exec-2-${Date.now()}`;

    // Execute concurrently with the SAME taskId
    const [outcome1, outcome2] = await Promise.all([
      testHarness.research(task1, { executionId: exec1 }),
      testHarness.research(task2, { executionId: exec2 }),
    ]);

    assert.strictEqual(outcome1.status, 'EXACT_MATCH');
    assert.strictEqual(outcome2.status, 'EXACT_MATCH');
    if (outcome1.status === 'EXACT_MATCH' && outcome2.status === 'EXACT_MATCH') {
      assert.strictEqual(outcome1.dossier.format, 'RSS_2_0');
      assert.strictEqual(outcome2.dossier.format, 'ATOM');
    }

    // Verify completed telemetry retention by executionId
    const history1 = testHarness.getTelemetryHistory(exec1);
    const history2 = testHarness.getTelemetryHistory(exec2);
    assert.ok(history1.length > 0, 'History for exec1 must be retained after completion');
    assert.ok(history2.length > 0, 'History for exec2 must be retained after completion');
    assert.strictEqual(history1[0].executionId, exec1);
    assert.strictEqual(history2[0].executionId, exec2);

    // Verify telemetry lookup by taskId returns latest completed
    const historyByTaskId = testHarness.getTelemetryHistory(sharedTaskId);
    assert.ok(historyByTaskId.length > 0, 'History lookup by taskId must succeed');
    console.log('  [PASS] Concurrent sessions with identical taskId isolated via executionId; history retained.');

    // ---------------------------------------------------------
    // 8. Explicit Error Statuses: CANCELLED, TIMED_OUT, ERROR (Point 4)
    // ---------------------------------------------------------
    console.log('\n--- 8. Testing Explicit Outcomes: CANCELLED, TIMED_OUT, ERROR (Point 4) ---');
    // A. Cancelled via external AbortSignal
    const preAbortedCtrl = new AbortController();
    preAbortedCtrl.abort(new Error('User manually cancelled operation'));
    const cancelOutcome = await testHarness.research(
      {
        id: `task-cancelled-${Date.now()}`,
        query: 'Cancelled test',
        feedUrl: `http://127.0.0.1:${serverPort}/valid-rss`,
      },
      { signal: preAbortedCtrl.signal }
    );
    assert.strictEqual(cancelOutcome.status, 'CANCELLED', 'Pre-aborted signal must produce CANCELLED');
    if (cancelOutcome.status === 'CANCELLED') {
      assert.ok(cancelOutcome.reason.includes('cancelled'));
    }

    // B. Cancelled via harness.cancel(executionId)
    const streamToCancel = testHarness.stream(
      {
        id: `task-cancel-exec-${Date.now()}`,
        query: 'Stream to cancel',
        feedUrl: `http://127.0.0.1:${serverPort}/hanging`,
      },
      { executionId: 'cancel-me-exec' }
    );
    const firstYieldPromise = streamToCancel.next();
    // Allow stream to enter execution
    await new Promise((r) => setTimeout(r, 50));
    const cancelSuccess = testHarness.cancel('cancel-me-exec', 'Test cancellation call');
    assert.strictEqual(cancelSuccess, true, 'harness.cancel by executionId must return true');

    let streamCancelledOutcome;
    let curr = await firstYieldPromise;
    while (!curr.done) {
      curr = await streamToCancel.next();
    }
    streamCancelledOutcome = curr.value;
    assert.strictEqual(streamCancelledOutcome.status, 'CANCELLED', 'Harness cancel must produce CANCELLED outcome');

    // C. Timed out on hanging endpoint
    const fastTimeoutHarness = new RssResearchHarness({
      timeoutMs: 300,
      allowPrivateForTesting: true,
    });
    const timedOutOutcome = await fastTimeoutHarness.research({
      id: `task-timeout-${Date.now()}`,
      query: 'Hanging endpoint test',
      feedUrl: `http://127.0.0.1:${serverPort}/hanging`,
    });
    assert.strictEqual(timedOutOutcome.status, 'TIMED_OUT', `Expected TIMED_OUT on hanging endpoint, got ${timedOutOutcome.status}`);
    if (timedOutOutcome.status === 'TIMED_OUT') {
      assert.ok(timedOutOutcome.reason.includes('timed out'), 'Reason must mention timed out');
      assert.ok(timedOutOutcome.elapsedMs !== undefined && timedOutOutcome.elapsedMs >= 0);
    }

    // D. Provider failure (HTTP 500) returns ERROR (not NOT_FOUND)
    // 1) Direct feed endpoint error -> RSS_FETCHER
    const errorDirectOutcome = await testHarness.research({
      id: `task-err500-dir-${Date.now()}`,
      query: 'HTTP 500 direct feed test',
      feedUrl: `http://127.0.0.1:${serverPort}/error-500.xml`,
    });
    assert.strictEqual(errorDirectOutcome.status, 'ERROR', `HTTP 500 direct must return ERROR`);
    if (errorDirectOutcome.status === 'ERROR') {
      assert.ok(errorDirectOutcome.error.includes('500'), 'Error message must mention HTTP 500');
      assert.strictEqual(errorDirectOutcome.provider, 'RSS_FETCHER');
    }

    // 2) Webpage discovery endpoint error -> FEED_DISCOVERY
    const errorDiscoveryOutcome = await testHarness.research({
      id: `task-err500-disc-${Date.now()}`,
      query: 'HTTP 500 discovery test',
      feedUrl: `http://127.0.0.1:${serverPort}/error-500`,
    });
    assert.strictEqual(errorDiscoveryOutcome.status, 'ERROR', `HTTP 500 discovery must return ERROR`);
    if (errorDiscoveryOutcome.status === 'ERROR') {
      assert.ok(errorDiscoveryOutcome.error.includes('500'), 'Error message must mention HTTP 500');
      assert.strictEqual(errorDiscoveryOutcome.provider, 'FEED_DISCOVERY');
    }
    console.log('  [PASS] Explicit CANCELLED, TIMED_OUT, and ERROR outcomes verified (exceptions never swallowed into NOT_FOUND).');

    // ---------------------------------------------------------
    // 9. Candidate Limit (Point 6)
    // ---------------------------------------------------------
    console.log('\n--- 9. Testing Candidate Limit (Point 6) ---');
    const disambigHarness = new RssResearchHarness({ maxCandidates: 2 });
    const secOutcome = await disambigHarness.research({
      id: `task-sec-limit-${Date.now()}`,
      query: 'sec filings for mergers',
    });
    assert.strictEqual(secOutcome.status, 'MULTIPLE_OPTIONS');
    if (secOutcome.status === 'MULTIPLE_OPTIONS') {
      assert.strictEqual(
        secOutcome.candidates.length,
        2,
        `Expected maxCandidates (2) to be respected, got ${secOutcome.candidates.length}`
      );
    }
    console.log('  [PASS] maxCandidates limit enforced for disambiguation options.');

    // ---------------------------------------------------------
    // 10. Strands SDK Tool Execution ID Forwarding (Point 10)
    // ---------------------------------------------------------
    console.log('\n--- 10. Testing Strands Tool executionId Forwarding (Point 10) ---');
    const tool = createRssResearchTool({ timeoutMs: 5000, allowPrivateForTesting: true });
    assert.strictEqual(tool.name, 'rss_research');

    const testExecutionId = `test-exec-${Date.now()}`;
    const toolStreamGen = tool.stream({
      toolUse: {
        name: 'rss_research',
        toolUseId: 'call-1',
        input: {
          query: 'Test tool forwarding',
          feedUrl: `http://127.0.0.1:${serverPort}/valid-rss`,
        },
      },
      invocationState: { taskId: 'tool-task-1', executionId: testExecutionId },
      cancelSignal: new AbortController().signal,
      agent: {} as any,
    });

    const receivedEvents: any[] = [];
    let toolStep = await toolStreamGen.next();
    while (!toolStep.done) {
      if (toolStep.value?.data) {
        receivedEvents.push(toolStep.value.data);
      }
      toolStep = await toolStreamGen.next();
    }
    assert.ok(receivedEvents.length > 0, 'Tool must yield telemetry events');
    assert.strictEqual(
      receivedEvents[0].executionId,
      testExecutionId,
      'Tool yielded telemetry event must include forwarded executionId'
    );

    const directInvoke = await tool.invoke({
      query: 'Test direct invoke',
      feedUrl: `http://127.0.0.1:${serverPort}/valid-rss`,
    });
    assert.strictEqual(directInvoke.status, 'EXACT_MATCH');
    console.log('  [PASS] Tool execution ID forwarded properly from context invocationState and direct invocation verified.');

    // ---------------------------------------------------------
    // 11. HTML Head Auto-Discovery & Empty Feed Handling
    // ---------------------------------------------------------
    console.log('\n--- 11. Testing HTML Head Sniffer & Empty Feeds ---');
    // Test HTML <link> auto discovery against live page
    const autoDiscOutcome = await testHarness.research({
      id: `task-autodisc-${Date.now()}`,
      query: 'Check blog',
      feedUrl: `http://127.0.0.1:${serverPort}/blog`,
    });
    assert.strictEqual(autoDiscOutcome.status, 'EXACT_MATCH', 'Auto-discovery from HTML page failed');
    if (autoDiscOutcome.status === 'EXACT_MATCH') {
      assert.ok(autoDiscOutcome.contract.feedUrl.includes('/valid-rss'));
    }

    // Test Feed with 0 articles
    const emptyOutcome = await testHarness.research({
      id: `task-empty-${Date.now()}`,
      query: 'Check empty feed',
      feedUrl: `http://127.0.0.1:${serverPort}/empty-feed`,
    });
    assert.strictEqual(emptyOutcome.status, 'NOT_FOUND', '0 articles feed must return NOT_FOUND');
    if (emptyOutcome.status === 'NOT_FOUND') {
      assert.ok(emptyOutcome.reason.includes('0 articles'));
    }

    // Direct check: discoverFeedFromUrl throws on non-abort errors (HTTP 500)
    await assert.rejects(
      async () => {
        await discoverFeedFromUrl(`http://127.0.0.1:${serverPort}/error-500`, {
          allowPrivateForTesting: true,
        });
      },
      (err: any) => {
        assert.ok(err instanceof ProviderError, 'Must be a ProviderError');
        assert.strictEqual(err.provider, 'FEED_DISCOVERY');
        assert.strictEqual(err.statusCode, 500);
        return true;
      },
      'discoverFeedFromUrl must throw ProviderError on HTTP 500 instead of returning []'
    );

    // Direct check: discoverFeedFromUrl throws on SSRF blocked metadata IP
    await assert.rejects(
      async () => {
        await discoverFeedFromUrl('http://169.254.169.254/latest/meta-data/');
      },
      (err: any) => {
        assert.ok(err instanceof ProviderError, 'Must be a ProviderError');
        assert.strictEqual(err.provider, 'FEED_DISCOVERY');
        assert.ok(err.message.includes('Blocked'));
        return true;
      },
      'discoverFeedFromUrl must throw ProviderError on SSRF block instead of returning []'
    );

    // Direct check: evaluateSemanticFilter fails closed on malformed output or throw
    const sampleItems = Array.from({ length: 25 }, (_, i) => ({
      title: i === 15 ? 'Quantum Leap 15' : `Item ${i}`,
      link: `http://example.com/${i}`,
      contentSnippet: `Snippet for article ${i}`,
      pubDate: Date.now() - i * 1000,
    }));

    // Case 1: Model returns malformed non-JSON
    const malformedModel = {
      streamAggregated: async function* () {
        return {
          message: new Message({
            role: 'assistant',
            content: [new TextBlock('Sorry, I am an LLM and cannot evaluate this.')],
          }),
          stopReason: 'endTurn',
          metadata: {},
        };
      },
    };
    await assert.rejects(
      async () => {
        await evaluateSemanticFilter(sampleItems, 'Quantum', malformedModel);
      },
      (err: any) => {
        assert.ok(err instanceof ProviderError);
        assert.strictEqual(err.provider, 'BEDROCK');
        assert.ok(err.message.includes('malformed output'));
        return true;
      },
      'evaluateSemanticFilter must throw ProviderError on malformed model output'
    );

    // Case 2: Model evaluates in batches of 10 and processes all items (0..24)
    let invokeBatchCount = 0;
    const batchingModel = {
      streamAggregated: async function* () {
        invokeBatchCount++;
        let matches: boolean[];
        if (invokeBatchCount === 1) {
          matches = Array(10).fill(false);
        } else if (invokeBatchCount === 2) {
          matches = Array(10).fill(false);
          matches[5] = true; // index 15 overall (batch 2, index 5)
        } else {
          matches = Array(5).fill(false);
          matches[2] = true; // index 22 overall (batch 3, index 2)
        }
        const responseText = JSON.stringify({ matches });

        return {
          message: new Message({
            role: 'assistant',
            content: [new TextBlock(responseText)],
          }),
          stopReason: 'endTurn',
          metadata: {},
        };
      },
    };
    const batchMatches = await evaluateSemanticFilter(sampleItems, 'Quantum', batchingModel);
    assert.strictEqual(batchMatches.length, 25, 'evaluateSemanticFilter must evaluate all 25 items');
    assert.strictEqual(invokeBatchCount, 3, '25 items in batches of 10 must invoke model 3 times (10, 10, 5)');
    assert.strictEqual(batchMatches[15], true, 'Item 15 must be matched');
    assert.strictEqual(batchMatches[22], true, 'Item 22 must be matched');
    assert.strictEqual(batchMatches[0], false, 'Item 0 must not be matched');
    assert.strictEqual(batchMatches[24], false, 'Item 24 must not be matched');
    console.log('  [PASS] HTML head sniffing, empty feeds, non-abort error propagation, and semantic batching/fail-closed verified.');

    // ---------------------------------------------------------
    // 12. Regex Detectors: GitHub Releases & Subreddits
    // ---------------------------------------------------------
    console.log('\n--- 12. Testing Specialized Pattern Detectors ---');
    const ghFeed = detectGithubReleaseFeed('watch releases for github.com/facebook/react');
    assert.strictEqual(ghFeed, 'https://github.com/facebook/react/releases.atom');

    const subFeed = detectSubredditFeed('alert me when r/LocalLLaMA posts a new fine-tune');
    assert.strictEqual(subFeed, 'https://www.reddit.com/r/LocalLLaMA/.rss');
    console.log('  [PASS] GitHub release and subreddit pattern detectors verified.');

    // ---------------------------------------------------------
    // 13. Production Feed Parser Hardening (URL Resolution, Media RSS, BOM, Entities, Timezones)
    // ---------------------------------------------------------
    console.log('\n--- 13. Testing Feed Parser Hardening Upgrades ---');

    // A. Relative URL resolution in Atom & RSS
    const atomRelativeXml = `
      <feed xmlns="http://www.w3.org/2005/Atom">
        <title>Relative Links Test</title>
        <link href="/feed.xml" rel="self" />
        <link href="/blog" rel="alternate" />
        <entry>
          <id>urn:uuid:1</id>
          <title>Relative Post</title>
          <link href="/posts/ai-breakthrough.html" />
          <media:thumbnail url="/images/thumb.png" />
        </entry>
      </feed>
    `;
    const parsedAtomRel = parseRawFeed(atomRelativeXml, 'https://example.com/sub/feed.xml');
    assert.strictEqual(parsedAtomRel.siteUrl, 'https://example.com/blog');
    assert.strictEqual(parsedAtomRel.items[0].link, 'https://example.com/posts/ai-breakthrough.html');
    assert.strictEqual(parsedAtomRel.items[0].enclosureUrl, 'https://example.com/images/thumb.png');
    console.log('  [PASS] Relative URLs in Atom links and media thumbnails resolved against base URL.');

    // B. RSS isPermaLink="false" Non-URL GUID Defense
    const rssGuidXml = `
      <rss version="2.0">
        <channel>
          <title>GUID Test</title>
          <item>
            <title>Non-URL GUID Post</title>
            <guid isPermaLink="false">uuid-99214-abc</guid>
          </item>
          <item>
            <title>URL GUID Post</title>
            <guid isPermaLink="true">https://example.com/p/valid-url</guid>
          </item>
        </channel>
      </rss>
    `;
    const parsedGuidRss = parseRawFeed(rssGuidXml, 'https://example.com/feed.xml');
    // Non-URL GUID must NOT become the link; should fall back to feedUrl
    assert.strictEqual(parsedGuidRss.items[0].link, 'https://example.com/feed.xml');
    // Valid URL GUID is accepted
    assert.strictEqual(parsedGuidRss.items[1].link, 'https://example.com/p/valid-url');
    console.log('  [PASS] isPermaLink="false" non-URL GUID prevented from polluting item links.');

    // C. Media RSS (YouTube / Substack) & iTunes Podcast Cover Extraction
    const mRssXml = `
      <rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
        <channel>
          <title>Media Feed</title>
          <item>
            <title>YouTube Video Post</title>
            <link>https://youtube.com/watch?v=123</link>
            <media:group>
              <media:thumbnail url="https://i.ytimg.com/vi/123/hqdefault.jpg" />
              <media:content url="https://youtube.com/v/123.mp4" />
            </media:group>
          </item>
          <item>
            <title>Podcast Episode</title>
            <link>https://podcast.com/ep1</link>
            <itunes:image href="https://podcast.com/art/ep1.jpg" />
          </item>
        </channel>
      </rss>
    `;
    const parsedMRss = parseRawFeed(mRssXml, 'https://youtube.com/feed');
    assert.strictEqual(parsedMRss.items[0].enclosureUrl, 'https://i.ytimg.com/vi/123/hqdefault.jpg');
    assert.strictEqual(parsedMRss.items[1].enclosureUrl, 'https://podcast.com/art/ep1.jpg');
    console.log('  [PASS] Media RSS (media:thumbnail) and iTunes image enclosures extracted accurately.');

    // D. UTF-8 Byte Order Mark (BOM) Defense
    const bomJsonFeed = '\uFEFF{"version": "https://jsonfeed.org/version/1.1", "title": "BOM JSON", "items": [{"id": "1", "title": "Post 1"}]}';
    const parsedBomJson = parseRawFeed(bomJsonFeed, 'https://json.com/feed.json');
    assert.strictEqual(parsedBomJson.format, 'JSON_FEED');
    assert.strictEqual(parsedBomJson.title, 'BOM JSON');

    const bomRss = '\uFEFF<?xml version="1.0"?><rss version="2.0"><channel><title>BOM RSS</title></channel></rss>';
    const parsedBomRss = parseRawFeed(bomRss, 'https://rss.com/feed.xml');
    assert.strictEqual(parsedBomRss.format, 'RSS_2_0');
    assert.strictEqual(parsedBomRss.title, 'BOM RSS');
    console.log('  [PASS] UTF-8 BOM stripped transparently for both JSON and XML feeds.');

    // E. Comprehensive Entity Decoding & Double-Escaping in sanitizeSnippet
    const trickySnippet = 'Apple&#8217;s latest chip &mdash; &#8220;M4 Max&#8221; &amp;quot;speed&amp;quot; &#x27;fast&#x27; &hellip; &copy; 2026';
    const cleanDecoded = sanitizeSnippet(trickySnippet);
    assert.strictEqual(cleanDecoded, 'Apple’s latest chip — “M4 Max” "speed" \'fast\' … © 2026');
    console.log('  [PASS] Typographic decimal/hex entities, double-escaped sequences, and symbols decoded.');

    // F. RFC 822 Timezone Normalization & Atom 0.3 Modified Date
    const estDate = parseDateSafe('Sun, 15 Jan 2026 14:00:00 EST');
    assert.ok(estDate.pubDate > 0);
    assert.strictEqual(estDate.isoDate, '2026-01-15T19:00:00.000Z'); // EST is UTC-5, so 14:00 EST == 19:00 UTC

    const pstDate = parseDateSafe('15 Jan 2026 11:00:00 PST');
    assert.ok(pstDate.pubDate > 0);
    assert.strictEqual(pstDate.isoDate, '2026-01-15T19:00:00.000Z'); // PST is UTC-8, so 11:00 PST == 19:00 UTC

    const atom03Xml = `
      <feed xmlns="http://purl.org/atom/ns#">
        <title>Atom 0.3 Feed</title>
        <modified>2026-09-08T12:00:00Z</modified>
        <entry>
          <title>Legacy Entry</title>
          <modified>2026-09-08T11:00:00Z</modified>
        </entry>
      </feed>
    `;
    const parsedAtom03 = parseRawFeed(atom03Xml, 'https://example.com/atom03.xml');
    assert.ok(parsedAtom03.lastBuildDate! > 0);
    assert.ok(parsedAtom03.items[0].pubDate > 0);
    console.log('  [PASS] RFC 822 timezones (EST/PST) and legacy Atom 0.3 modified timestamps parsed.');

    console.log('\n==========================================================');
    console.log('✅ ALL 13 PRODUCTION RSS META-HARNESS TEST MODULES PASSED!');
    console.log('==========================================================\n');
  } finally {
    server.close();
  }
}

runRssTests().catch((err) => {
  console.error('\n❌ RSS Harness test execution failed:', err);
  process.exit(1);
});

